/**
 * This is a main entrypoint for style rules.
 */

export default {
	extends: [
		'stylelint-config-standard',
		'stylelint-config-standard-scss',
	],
	ignoreFiles: [
		'node_modules/**/*.{css,scss,sass}',
		'public/**/*.{css,scss,sass}',
		'templates/**/*.{css,scss,sass}',
		'tests/**/*.{css,scss,sass}',
		'var/**/*.{css,scss,sass}',
		'vendor/**/*.{css,scss,sass}',
	],
	plugins: [
		"@stylistic/stylelint-plugin"
	],
	rules: {
		// Stylint.
		'no-descending-specificity': null,
		'declaration-block-no-duplicate-custom-properties': true,
		'declaration-block-no-duplicate-properties': true,
		'no-duplicate-selectors': true,
		'block-no-empty': true,
		'color-no-invalid-hex': true,
		'function-calc-no-unspaced-operator': true,
		'string-no-newline': true,
		"no-irregular-whitespace": true,
		'function-linear-gradient-no-nonstandard-direction': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'no-unknown-animations': true,
		'unit-no-unknown': true,
		'at-rule-no-vendor-prefix': true,
		'color-named': null,
		'declaration-no-important': true,
		'length-zero-no-unit': true,
		'media-feature-name-no-vendor-prefix': true,
		'property-no-vendor-prefix': true,
		'selector-no-vendor-prefix': true,
		'value-no-vendor-prefix': true,
		'value-keyword-case': null,
		'comment-empty-line-before': [
			'always', {
				ignore: ['stylelint-commands', 'after-comment'],
			},
		],
		'declaration-empty-line-before': null,
		'rule-empty-line-before': [
			'always', {
				except: ['first-nested'],
				ignore: ['after-comment'],
			},
		],
		'declaration-block-single-line-max-declarations': 1,
		'max-nesting-depth': 5,
		'number-max-precision': 3,
		'selector-max-specificity': '0,4,0',
		'alpha-value-notation': 'number',
		'color-function-notation': null,
		'font-weight-notation': 'named-where-possible',
		'selector-pseudo-element-colon-notation': 'double',
		'color-hex-length': 'long',
		'selector-class-pattern': null,
		'keyframes-name-pattern': null,
		'font-family-name-quotes': 'always-unless-keyword',
		'function-url-quotes': 'always',
		'declaration-block-no-redundant-longhand-properties': [
			true,
			{
				ignoreShorthands: ["/grid/"]
			},
		],
		'comment-whitespace-inside': 'always',
		// Stylelistic.
		'@stylistic/color-hex-case': 'upper',
		'@stylistic/function-comma-space-after': 'always',
		'@stylistic/function-comma-space-before': 'never',
		'@stylistic/function-parentheses-newline-inside': 'never-multi-line',
		'@stylistic/function-parentheses-space-inside': 'never',
		'@stylistic/function-whitespace-after': 'always',
		'@stylistic/number-leading-zero': 'always',
		'@stylistic/number-no-trailing-zeros': true,
		'@stylistic/string-quotes': 'single',
		'@stylistic/value-list-comma-newline-before': 'never-multi-line',
		'@stylistic/value-list-comma-newline-after': null,
		'@stylistic/value-list-comma-space-before': 'never',
		'@stylistic/value-list-comma-space-after': 'always-single-line',
		'@stylistic/value-list-max-empty-lines': 1,
		'@stylistic/declaration-bang-space-after': 'never',
		'@stylistic/declaration-bang-space-before': 'always',
		'@stylistic/declaration-colon-newline-after': null,
		'@stylistic/declaration-colon-space-before': 'never',
		'@stylistic/declaration-colon-space-after': 'always-single-line',
		'@stylistic/declaration-block-semicolon-newline-after': 'always',
		'@stylistic/declaration-block-semicolon-newline-before': 'never-multi-line',
		'@stylistic/declaration-block-semicolon-space-after': 'always-single-line',
		'@stylistic/declaration-block-semicolon-space-before': 'never',
		'@stylistic/declaration-block-trailing-semicolon': 'always',
		'@stylistic/block-closing-brace-newline-after': 'always',
		'@stylistic/block-closing-brace-newline-before': 'always',
		'@stylistic/block-opening-brace-newline-after': 'always',
		'@stylistic/block-opening-brace-newline-before': 'always-single-line',
		'@stylistic/block-opening-brace-space-before': 'always',
		'@stylistic/selector-combinator-space-after': 'always',
		'@stylistic/selector-combinator-space-before': 'always',
		'@stylistic/selector-list-comma-newline-after': 'always',
		'@stylistic/selector-list-comma-newline-before': 'never-multi-line',
		'@stylistic/media-feature-colon-space-after': 'always',
		'@stylistic/media-feature-colon-space-before': 'never',
		'@stylistic/media-feature-range-operator-space-after': 'always',
		'@stylistic/media-feature-range-operator-space-before': 'always',
		'@stylistic/indentation': 'tab',
		'@stylistic/max-empty-lines': 2,
		'@stylistic/max-line-length': 250,
		'@stylistic/no-eol-whitespace': true,
	}
};
